worker_processes 1;
error_log /var/log/nginx/error.log warn;
pid /run/nginx.pid;

events { worker_connections 256; }

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;

    log_format main '$remote_addr - $remote_user [$time_local] '
                    '"$request" $status $body_bytes_sent '
                    '"$http_referer" "$http_user_agent"';
    access_log /var/log/nginx/access.log main;

    server {
        listen 80 default_server;
        server_name _;
        root /var/www/html;
        index index.php index.html;

        location / {
            try_files $uri $uri/ =404;
        }

        location /backup/ {
            autoindex on;
            autoindex_exact_size off;
        }

        # /private dir served only via direct file access (NOT directory listed).
        # This lets LFI succeed but blind enumeration not.
        location /private/ {
            deny all;
            return 403;
        }

        location ~ \.php$ {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }

        # Block direct download of .env via web (it should leak only via LFI)
        location ~ /\.env {
            deny all;
            return 403;
        }
    }
}
